package com.souru.lumina.data.luts

/**
 * 標準搭載のLUTプリセット。すべて数学的に自前生成した.cubeデータで、
 * 実在ブランドのLUTファイルや名称は使用しない(Playストア公開時の
 * 商標・権利リスク回避)。
 *
 * いずれもLog系(低コントラスト・低彩度、S-Cinetone for Mobile等)の
 * 入力を前提にトーンカーブを設計している。Rec.709素材に当てると
 * 濃すぎる場合がある。
 */
enum class LutPreset(val displayName: String, val fileName: String) {
    TEAL_ORANGE("Teal & Orange", "Teal & Orange.cube"),
    CINEMATIC_WARM("Cinematic Warm", "Cinematic Warm.cube"),
    CHROME_FILM("Chrome Film", "Chrome Film.cube"),
    NOSTALGIC_FILM("Nostalgic Film", "Nostalgic Film.cube"),
    CLEAN_CONTRAST("Clean Contrast", "Clean Contrast.cube"),
    MONO_CINEMA("Mono Cinema", "Mono Cinema.cube"),
}

object LutPresets {

    const val SIZE = 33

    /** プリセット生成アルゴリズムの版。変えると既存生成物が再生成される。 */
    const val VERSION = 1

    /**
     * 1色を変換する。入出力とも0..1。
     *
     * 設計メモ: トーンカーブは「線形成分0.15 + smoothstep0.85」の合成で、
     * グレー軸上の傾きが常に0.15以上になる。スプリットトーン等の色シフトは
     * 輝度の滑らかな関数で傾きの絶対値が0.21未満のため、グレー軸に沿った
     * 単調性が構造的に保たれる(ユニットテストで検証)。
     */
    fun transform(preset: LutPreset, r0: Float, g0: Float, b0: Float): FloatArray {
        var r: Float
        var g: Float
        var b: Float
        when (preset) {
            LutPreset.CLEAN_CONTRAST -> {
                // Log→709の基本変換: コントラストと彩度の復元のみ
                r = tone(r0, 0.05f, 0.95f)
                g = tone(g0, 0.05f, 0.95f)
                b = tone(b0, 0.05f, 0.95f)
                val l = luma(r, g, b)
                r = sat(r, l, 1.25f)
                g = sat(g, l, 1.25f)
                b = sat(b, l, 1.25f)
            }

            LutPreset.TEAL_ORANGE -> {
                r = tone(r0, 0.05f, 0.95f)
                g = tone(g0, 0.05f, 0.95f)
                b = tone(b0, 0.05f, 0.95f)
                val l = luma(r, g, b)
                r = sat(r, l, 1.15f)
                g = sat(g, l, 1.15f)
                b = sat(b, l, 1.15f)
                // シャドウ→ティール、ハイライト→オレンジのスプリットトーン
                val sw = (1f - l) * (1f - l)
                val hw = l * l
                r += -0.045f * sw + 0.055f * hw
                g += 0.012f * sw + 0.018f * hw
                b += 0.055f * sw - 0.050f * hw
            }

            LutPreset.CINEMATIC_WARM -> {
                r = tone(r0, 0.04f, 0.93f)
                g = tone(g0, 0.04f, 0.93f)
                b = tone(b0, 0.04f, 0.93f)
                var l = luma(r, g, b)
                // 緑を落ち着かせる(緑チャンネルを輝度へ少し寄せる)
                g += (l - g) * 0.10f
                l = luma(r, g, b)
                r = sat(r, l, 1.08f)
                g = sat(g, l, 1.08f)
                b = sat(b, l, 1.08f)
                // 暖色寄りのハイライト
                val hw = l * l
                r += 0.012f + 0.030f * hw
                b -= 0.028f
                // わずかなフェード
                r = 0.022f + r * 0.965f
                g = 0.022f + g * 0.965f
                b = 0.022f + b * 0.965f
            }

            LutPreset.CHROME_FILM -> {
                // シャドウ締め気味のドキュメンタリー調
                r = tone(r0, 0.08f, 0.92f)
                g = tone(g0, 0.08f, 0.92f)
                b = tone(b0, 0.08f, 0.92f)
                var l = luma(r, g, b)
                // 青をくすませる
                b += (l - b) * 0.18f
                l = luma(r, g, b)
                r = sat(r, l, 0.80f)
                g = sat(g, l, 0.80f)
                b = sat(b, l, 0.80f)
                r -= 0.008f
            }

            LutPreset.NOSTALGIC_FILM -> {
                // 低コントラスト+フェードした黒+暖色シフト
                r = tone(r0, 0.02f, 0.98f)
                g = tone(g0, 0.02f, 0.98f)
                b = tone(b0, 0.02f, 0.98f)
                val l = luma(r, g, b)
                r = sat(r, l, 0.88f)
                g = sat(g, l, 0.88f)
                b = sat(b, l, 0.88f)
                r += 0.030f
                b -= 0.035f
                r = 0.06f + r * 0.90f
                g = 0.06f + g * 0.90f
                b = 0.06f + b * 0.90f
            }

            LutPreset.MONO_CINEMA -> {
                // 赤フィルター気味のフィルム調モノクロ
                val gray = 0.50f * r0 + 0.36f * g0 + 0.14f * b0
                val v = tone(gray, 0.05f, 0.95f)
                r = v
                g = v
                b = v
            }
        }
        return floatArrayOf(clamp01(r), clamp01(g), clamp01(b))
    }

    /** .cubeテキスト(Adobe Cube LUT Specification 1.0 サブセット)を生成する。 */
    fun generateCubeText(preset: LutPreset, size: Int = SIZE): String {
        val sb = StringBuilder(size * size * size * 24)
        sb.append("TITLE \"Lumina ").append(preset.displayName).append("\"\n")
        sb.append("# Generated by Lumina (v").append(VERSION).append("). Log素材向け\n")
        sb.append("LUT_3D_SIZE ").append(size).append('\n')
        sb.append("DOMAIN_MIN 0.0 0.0 0.0\n")
        sb.append("DOMAIN_MAX 1.0 1.0 1.0\n")
        val maxIndex = (size - 1).toFloat()
        // .cubeはRが最も速く変化する順
        for (bi in 0 until size) {
            for (gi in 0 until size) {
                for (ri in 0 until size) {
                    val out = transform(preset, ri / maxIndex, gi / maxIndex, bi / maxIndex)
                    sb.append(fmt(out[0])).append(' ')
                        .append(fmt(out[1])).append(' ')
                        .append(fmt(out[2])).append('\n')
                }
            }
        }
        return sb.toString()
    }

    private fun fmt(v: Float): String = "%.6f".format(java.util.Locale.US, v)

    /**
     * Log素材を持ち上げるS字トーン。線形成分を混ぜて端でも傾きが
     * 0.15を下回らないようにする(単調性の保証)。
     */
    private fun tone(x: Float, lo: Float, hi: Float): Float =
        0.15f * x + 0.85f * smoothstep(lo, hi, x)

    private fun sat(c: Float, l: Float, factor: Float): Float = l + (c - l) * factor

    private fun luma(r: Float, g: Float, b: Float): Float =
        0.2126f * r + 0.7152f * g + 0.0722f * b

    private fun smoothstep(edge0: Float, edge1: Float, x: Float): Float {
        val t = ((x - edge0) / (edge1 - edge0)).coerceIn(0f, 1f)
        return t * t * (3f - 2f * t)
    }

    private fun clamp01(v: Float): Float = v.coerceIn(0f, 1f)
}
