#!/usr/bin/env python3
"""Generates the iOS app icon in the three appearances iOS 18+ asks for.

Android source of truth:
  app/src/main/res/drawable/ic_launcher_background.xml  (pastel diagonal wash)
  app/src/main/res/drawable/ic_launcher_foreground.xml  (sweep-gradient wheel + dot)

The adaptive icon's visible area is the central 72dp of the 108dp canvas, so we
map that 72dp square onto the full-bleed 1024px iOS icon (scale = 1024/72).
SVG has no sweep/conic gradient, so the wheel stroke is approximated with 180
solid 2-degree arc segments interpolated between the Android gradient stops.

Outputs:
  icon.svg / icon-1024.png    light   - the pastel wash, as Android shows it
  icon-dark-1024.png          dark    - same wheel on the app's own dark base
  icon-tinted-1024.png        tinted  - greyscale; iOS multiplies it by the
                                        user's tint, so luminance alone has to
                                        carry the shape

Usage:  python3 gen_icon.py
"""
import math

S = 1024 / 72.0                      # adaptive visible 72dp -> 1024px
CX = CY = 512.0
RING_R = 29 * S                      # 412.2
RING_W = 12 * S                      # 170.7
DOT_X = CX + (34.6 - 54) * S         # picker dot, same spot as Android
DOT_Y = CY + (75.5 - 54) * S
DOT_R = 7.5 * S
DOT_STROKE_W = 1.5 * S

# Android sweep gradient stops: fraction (0 = 3 o'clock, clockwise), color.
STOPS = [
    (0.00, "FF3B30"), (0.12, "FF9500"), (0.25, "FFCC00"), (0.38, "34C759"),
    (0.50, "00C7BE"), (0.62, "32ADE6"), (0.75, "5E5CE6"), (0.87, "AF52DE"),
    (0.94, "FF2D92"), (1.00, "FF3B30"),
]

SEGMENTS = 180
OVERLAP = 0.6  # degrees; hides hairline seams between butt-capped arcs


def color_at(frac: float) -> str:
    for (f0, c0), (f1, c1) in zip(STOPS, STOPS[1:]):
        if f0 <= frac <= f1:
            t = 0.0 if f1 == f0 else (frac - f0) / (f1 - f0)
            rgb0 = [int(c0[i:i + 2], 16) for i in (0, 2, 4)]
            rgb1 = [int(c1[i:i + 2], 16) for i in (0, 2, 4)]
            return "#%02X%02X%02X" % tuple(
                round(a + (b - a) * t) for a, b in zip(rgb0, rgb1))
    return "#" + STOPS[-1][1]


def grey_at(frac: float) -> str:
    """The wheel colour as luminance, compressed into a band that survives
    tinting. Raw Rec.601 luminance would put yellow near white and blue near
    black, so the ring is mapped into 0.45-0.85 and the hue only modulates
    within that — the wheel still reads as a ring, not as a gap."""
    hexcol = color_at(frac).lstrip("#")
    r, g, b = (int(hexcol[i:i + 2], 16) / 255 for i in (0, 2, 4))
    lum = 0.299 * r + 0.587 * g + 0.114 * b
    n = round((0.45 + 0.40 * lum) * 255)
    return "#%02X%02X%02X" % (n, n, n)


def pt(angle_deg: float):
    # Screen coords (y down): increasing angle from east == clockwise, matching
    # Android's SweepGradient direction.
    a = math.radians(angle_deg)
    return CX + RING_R * math.cos(a), CY + RING_R * math.sin(a)


def background(appearance: str) -> list:
    """Light keeps Android's pastel wash. Dark uses the app's own base so the
    icon sits in the same world as the UI. Tinted must be a flat dark field,
    because iOS tints the entire image and a gradient would tint unevenly."""
    if appearance == "tinted":
        return ['  <rect width="1024" height="1024" fill="#0B0B0B"/>']
    stops = ([("0", "#F5EEFF"), ("0.5", "#FFE7F1"), ("1", "#FFF1E8")]
             if appearance == "light"
             else [("0", "#16121F"), ("0.55", "#101014"), ("1", "#1A1218")])
    out = ['  <defs>',
           '    <linearGradient id="bg" gradientUnits="userSpaceOnUse" '
           'x1="0" y1="0" x2="1024" y2="1024">']
    out += [f'      <stop offset="{o}" stop-color="{c}"/>' for o, c in stops]
    out += ['    </linearGradient>', '  </defs>',
            '  <rect width="1024" height="1024" fill="url(#bg)"/>']
    return out


def build_svg(appearance: str) -> str:
    """appearance: 'light' | 'dark' | 'tinted'."""
    parts = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!--",
        "  ColorHunt app icon - GENERATED by gen_icon.py. Do not hand-edit;",
        "  edit the Android launcher drawables (the design source) or the",
        "  generator, then re-run: python3 gen_icon.py",
        f"  Appearance: {appearance}.",
        "  iOS masks the squircle itself - keep square corners here.",
        "-->",
        '<svg width="1024" height="1024" viewBox="0 0 1024 1024" '
        'xmlns="http://www.w3.org/2000/svg">',
    ]
    parts += background(appearance)

    for i in range(SEGMENTS):
        a0 = i * 360.0 / SEGMENTS
        a1 = (i + 1) * 360.0 / SEGMENTS + OVERLAP
        mid = (a0 + (i + 1) * 360.0 / SEGMENTS) / 2
        x0, y0 = pt(a0)
        x1, y1 = pt(a1)
        frac = (mid % 360) / 360.0
        c = grey_at(frac) if appearance == "tinted" else color_at(frac)
        parts.append(
            f'  <path d="M{x0:.2f} {y0:.2f} A{RING_R:.2f} {RING_R:.2f} 0 0 1 '
            f'{x1:.2f} {y1:.2f}" fill="none" stroke="{c}" '
            f'stroke-width="{RING_W:.2f}"/>')

    # The picker dot. On the pastel wash it needs the hairline Android gives
    # it; on the dark backgrounds it separates on its own, and staying pure
    # white keeps it the brightest thing in the tinted version.
    dot = (f'  <circle cx="{DOT_X:.2f}" cy="{DOT_Y:.2f}" r="{DOT_R:.2f}" '
           f'fill="#FFFFFF"')
    if appearance == "light":
        dot += (f' stroke="#000000" stroke-opacity="0.133" '
                f'stroke-width="{DOT_STROKE_W:.2f}"')
    parts.append(dot + '/>')
    parts.append('</svg>')
    return "\n".join(parts) + "\n"


import cairosvg  # noqa: E402

for appearance, name in [("light", "icon"), ("dark", "icon-dark"),
                         ("tinted", "icon-tinted")]:
    svg = build_svg(appearance)
    # Every appearance keeps its SVG so each one can be opened and edited in a
    # vector tool, not just the light master.
    with open(f"{name}.svg", "w") as f:
        f.write(svg)
    cairosvg.svg2png(url=f"{name}.svg", write_to=f"{name}-1024.png",
                     output_width=1024, output_height=1024)
    print(f"wrote {name}.svg + {name}-1024.png")
