#!/usr/bin/env python3
"""Generates the iOS app icon to match the Android launcher icon exactly.

Android source of truth:
  app/src/main/res/drawable/ic_launcher_background.xml  (pastel diagonal wash)
  app/src/main/res/drawable/ic_launcher_foreground.xml  (sweep-gradient wheel + dot)

The adaptive icon's visible area is the central 72dp of the 108dp canvas, so we
map that 72dp square onto the full-bleed 1024px iOS icon (scale = 1024/72).
SVG has no sweep/conic gradient, so the wheel stroke is approximated with 180
solid 2-degree arc segments interpolated between the Android gradient stops.

Usage:  python3 gen_icon.py   (writes icon.svg and icon-1024.png)
"""
import math

S = 1024 / 72.0                      # adaptive visible 72dp -> 1024px
CX = CY = 512.0
RING_R = 29 * S                      # 412.2
RING_W = 12 * S                      # 170.7
DOT_X = CX + (34.6 - 54) * S         # picker dot, same spot as Android
DOT_Y = CY + (75.5 - 54) * S
DOT_R = 7.5 * S
DOT_STROKE_W = 1.5 * S

# Android sweep gradient stops: fraction (0 = 3 o'clock, clockwise), color.
STOPS = [
    (0.00, "FF3B30"), (0.12, "FF9500"), (0.25, "FFCC00"), (0.38, "34C759"),
    (0.50, "00C7BE"), (0.62, "32ADE6"), (0.75, "5E5CE6"), (0.87, "AF52DE"),
    (0.94, "FF2D92"), (1.00, "FF3B30"),
]


def color_at(frac: float) -> str:
    for (f0, c0), (f1, c1) in zip(STOPS, STOPS[1:]):
        if f0 <= frac <= f1:
            t = 0.0 if f1 == f0 else (frac - f0) / (f1 - f0)
            rgb0 = [int(c0[i:i + 2], 16) for i in (0, 2, 4)]
            rgb1 = [int(c1[i:i + 2], 16) for i in (0, 2, 4)]
            return "#%02X%02X%02X" % tuple(
                round(a + (b - a) * t) for a, b in zip(rgb0, rgb1))
    return "#" + STOPS[-1][1]


def pt(angle_deg: float):
    # Screen coords (y down): increasing angle from east == clockwise, matching
    # Android's SweepGradient direction.
    a = math.radians(angle_deg)
    return CX + RING_R * math.cos(a), CY + RING_R * math.sin(a)


SEGMENTS = 180
OVERLAP = 0.6  # degrees; hides hairline seams between butt-capped arcs

parts = []
parts.append('<?xml version="1.0" encoding="UTF-8"?>')
parts.append("<!--")
parts.append("  ColorHunt app icon - GENERATED by gen_icon.py. Do not hand-edit;")
parts.append("  edit the Android launcher drawables (the design source) or the")
parts.append("  generator, then re-run: python3 gen_icon.py")
parts.append("  Design parity with Android: pastel lavender-pink-peach wash, the")
parts.append("  colour-wheel ring, and the white picker dot (the hunt).")
parts.append("  iOS masks the squircle itself - keep square corners here.")
parts.append("-->")
parts.append('<svg width="1024" height="1024" viewBox="0 0 1024 1024" '
             'xmlns="http://www.w3.org/2000/svg">')
parts.append('  <defs>')
parts.append('    <linearGradient id="bg" gradientUnits="userSpaceOnUse" '
             'x1="0" y1="0" x2="1024" y2="1024">')
parts.append('      <stop offset="0" stop-color="#F5EEFF"/>')
parts.append('      <stop offset="0.5" stop-color="#FFE7F1"/>')
parts.append('      <stop offset="1" stop-color="#FFF1E8"/>')
parts.append('    </linearGradient>')
parts.append('  </defs>')
parts.append('  <rect width="1024" height="1024" fill="url(#bg)"/>')

for i in range(SEGMENTS):
    a0 = i * 360.0 / SEGMENTS
    a1 = (i + 1) * 360.0 / SEGMENTS + OVERLAP
    mid = (a0 + (i + 1) * 360.0 / SEGMENTS) / 2
    x0, y0 = pt(a0)
    x1, y1 = pt(a1)
    c = color_at((mid % 360) / 360.0)
    parts.append(
        f'  <path d="M{x0:.2f} {y0:.2f} A{RING_R:.2f} {RING_R:.2f} 0 0 1 '
        f'{x1:.2f} {y1:.2f}" fill="none" stroke="{c}" '
        f'stroke-width="{RING_W:.2f}"/>')

parts.append(
    f'  <circle cx="{DOT_X:.2f}" cy="{DOT_Y:.2f}" r="{DOT_R:.2f}" '
    f'fill="#FFFFFF" stroke="#000000" stroke-opacity="0.133" '
    f'stroke-width="{DOT_STROKE_W:.2f}"/>')
parts.append('</svg>')

with open("icon.svg", "w") as f:
    f.write("\n".join(parts) + "\n")

import cairosvg  # noqa: E402
cairosvg.svg2png(url="icon.svg", write_to="icon-1024.png",
                 output_width=1024, output_height=1024)
print("wrote icon.svg + icon-1024.png")
